export enum ActionType {
	MOVE_VAULT = "MOVE_VAULT",
	DELETE_VAULT = "DELETE_VAULT",
	INSERT_VAULT_AFTER = "INSERT_VAULT_AFTER",
	UPDATE_VAULT = "UPDATE_VAULT",
	BUNDLE_START = "BUNDLE_START",
	BUNDLE_COMPLETE = "BUNDLE_COMPLETE"
}
